# Generated by Django 3.1.7 on 2021-03-28 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainiary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='datetime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
