# Generated by Django 3.1.7 on 2021-04-25 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainiary_app', '0003_auto_20210425_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
