# Generated by Django 3.1.7 on 2021-04-25 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainiary_app', '0004_auto_20210425_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='datetime',
            new_name='end',
        ),
        migrations.AddField(
            model_name='workout',
            name='allday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
