# Generated by Django 3.1.7 on 2021-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainiary_app', '0006_auto_20210425_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='myevent',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
