# Generated by Django 3.1.7 on 2021-05-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainiary_app', '0013_auto_20210521_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myevent',
            old_name='user_id',
            new_name='user',
        ),
    ]
