# Generated by Django 3.1.7 on 2021-05-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainiary_app', '0007_myevent_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='myevent',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='myevent',
            name='intensity',
            field=models.IntegerField(),
        ),
    ]
